import "dotenv/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL is missing");
}

const pool = new Pool({
  connectionString,
});

const adapter = new PrismaPg(pool as any);
const prisma = new PrismaClient({ adapter });

async function main() {
  await prisma.blade.createMany({
    data: [
      {
        name: "Rhino Horn",
        category: "DEFENSE",
        spin: "R",
        attack: 20,
        defense: 50,
        stamina: 30,
        weight: 32.15,
        height: 13.72,
        width: 45.05,
      },
      {
        name: "Samurai Saber",
        category: "ATTACK",
        spin: "R",
        attack: 65,
        defense: 20,
        stamina: 25,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Roar Tyranno",
        category: "ATTACK",
        spin: "R",
        attack: 60,
        defense: 28,
        stamina: 12,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Samurai Steel",
        category: "STAMINA",
        spin: "R",
        attack: 40,
        defense: 37,
        stamina: 23,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Scorpio Spear",
        category: "ATTACK",
        spin: "R",
        attack: 25,
        defense: 55,
        stamina: 30,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Shark Edge",
        category: "ATTACK",
        spin: "R",
        attack: 60,
        defense: 25,
        stamina: 15,
        weight: 34.53,
        height: 14.25,
        width: 48.88,
      },
      {
        name: "Shelter Drake",
        category: "BALANCE",
        spin: "R",
        attack: 25,
        defense: 40,
        stamina: 35,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Shinobi Knife",
        category: "DEFENSE",
        spin: "R",
        attack: 23,
        defense: 50,
        stamina: 27,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Shinobi Shadow",
        category: "DEFENSE",
        spin: "R",
        attack: 10,
        defense: 70,
        stamina: 20,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Silver Wolf",
        category: "STAMINA",
        spin: "R",
        attack: 15,
        defense: 30,
        stamina: 65,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Sphinx Cowl",
        category: "DEFENSE",
        spin: "R",
        attack: 35,
        defense: 55,
        stamina: 10,
        weight: 32.58,
        height: 13.60,
        width: 47.90,
      },
      {
        name: "Tricera Press",
        category: "DEFENSE",
        spin: "R",
        attack: 20,
        defense: 65,
        stamina: 15,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Tyranno Beat",
        category: "ATTACK",
        spin: "R",
        attack: 65,
        defense: 30,
        stamina: 5,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Unicorn Sting",
        category: "ATTACK",
        spin: "R",
        attack: 35,
        defense: 35,
        stamina: 30,
        weight: 33.23,
        height: 13.80,
        width: 48.10,
      },
      {
        name: "Viper Tail",
        category: "STAMINA",
        spin: "R",
        attack: 30,
        defense: 20,
        stamina: 50,
        weight: 34.71,
        height: 13.82,
        width: 48.35,
      },
      {
        name: "Weiss Tiger",
        category: "BALANCE",
        spin: "R",
        attack: 45,
        defense: 30,
        stamina: 25,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Whale Wave",
        category: "BALANCE",
        spin: "R",
        attack: 45,
        defense: 35,
        stamina: 20,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Wizard Arrow",
        category: "STAMINA",
        spin: "R",
        attack: 15,
        defense: 30,
        stamina: 55,
        weight: 31.97,
        height: 14.06,
        width: 48.09,
      },
      {
        name: "Wizard Rod",
        category: "STAMINA",
        spin: "R",
        attack: 15,
        defense: 25,
        stamina: 60,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Wyvern Gale",
        category: "STAMINA",
        spin: "R",
        attack: 10,
        defense: 40,
        stamina: 50,
        weight: 31.67,
        height: 14.15,
        width: 48.20,
      },
            {
        name: "Dran Buster",
        category: "ATTACK",
        spin: "R",
        attack: 70,
        defense: 20,
        stamina: 10,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Dran Dagger",
        category: "ATTACK",
        spin: "R",
        attack: 50,
        defense: 25,
        stamina: 25,
        weight: 34.60,
        height: 14.09,
        width: 47.54,
      },
      {
        name: "Dran Sword",
        category: "ATTACK",
        spin: "R",
        attack: 55,
        defense: 25,
        stamina: 20,
        weight: 34.67,
        height: 14.12,
        width: 48.25,
      },
      {
        name: "Ghost Circle",
        category: "STAMINA",
        spin: "B",
        attack: 5,
        defense: 40,
        stamina: 55,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Golem Rock",
        category: "DEFENSE",
        spin: "R",
        attack: 30,
        defense: 60,
        stamina: 10,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Hells Chain",
        category: "BALANCE",
        spin: "B",
        attack: 35,
        defense: 40,
        stamina: 25,
        weight: 33.22,
        height: 13.58,
        width: 48.13,
      },
      {
        name: "Hells Hammer",
        category: "BALANCE",
        spin: "R",
        attack: 50,
        defense: 25,
        stamina: 25,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Hells Scythe",
        category: "BALANCE",
        spin: "R",
        attack: 30,
        defense: 35,
        stamina: 35,
        weight: 32.70,
        height: 14.29,
        width: 47.99,
      },
      {
        name: "Impact Drake",
        category: "ATTACK",
        spin: "R",
        attack: 75,
        defense: 25,
        stamina: 10,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Knight Lance",
        category: "DEFENSE",
        spin: "R",
        attack: 25,
        defense: 60,
        stamina: 15,
        weight: 32.94,
        height: 13.95,
        width: 47.44,
      },
      {
        name: "Knight Mail",
        category: "DEFENSE",
        spin: "R",
        attack: 10,
        defense: 65,
        stamina: 35,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Knight Shield",
        category: "DEFENSE",
        spin: "R",
        attack: 20,
        defense: 55,
        stamina: 25,
        weight: 32.48,
        height: 14.14,
        width: 47.99,
      },
      {
        name: "Leon Claw",
        category: "BALANCE",
        spin: "R",
        attack: 40,
        defense: 40,
        stamina: 20,
        weight: 31.30,
        height: 13.91,
        width: 48.34,
      },
      {
        name: "Leon Crest",
        category: "DEFENSE",
        spin: "R",
        attack: 15,
        defense: 70,
        stamina: 15,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Mammoth Tusk",
        category: "STAMINA",
        spin: "R",
        attack: 33,
        defense: 35,
        stamina: 32,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Phoenix Feather",
        category: "ATTACK",
        spin: "R",
        attack: 50,
        defense: 20,
        stamina: 30,
        weight: 33.04,
        height: 14.55,
        width: 48.50,
      },
      {
        name: "Phoenix Rudder",
        category: "STAMINA",
        spin: "R",
        attack: 15,
        defense: 40,
        stamina: 60,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Phoenix Wing",
        category: "ATTACK",
        spin: "R",
        attack: 65,
        defense: 30,
        stamina: 20,
        weight: 37.95,
        height: 13.70,
        width: 49.00,
      },
      {
        name: "Ptera Swing",
        category: "STAMINA",
        spin: "R",
        attack: 27,
        defense: 23,
        stamina: 50,
        weight: 0,
        height: 0,
        width: 0,
      },
            {
        name: "Aero Pegasus",
        category: "ATTACK",
        spin: "R",
        attack: 65,
        defense: 30,
        stamina: 35,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Bear Scratch",
        category: "DEFENSE",
        spin: "R",
        attack: 25,
        defense: 45,
        stamina: 30,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Black Shell",
        category: "DEFENSE",
        spin: "R",
        attack: 10,
        defense: 65,
        stamina: 25,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Cobalt Dragoon",
        category: "ATTACK",
        spin: "L",
        attack: 60,
        defense: 15,
        stamina: 25,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Cobalt Drake",
        category: "ATTACK",
        spin: "B",
        attack: 70,
        defense: 35,
        stamina: 25,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Crimson Garuda",
        category: "BALANCE",
        spin: "R",
        attack: 45,
        defense: 25,
        stamina: 30,
        weight: 0,
        height: 0,
        width: 0,
      },
      {
        name: "Croco Crunch",
        category: "ATTACK",
        spin: "R",
        attack: 60,
        defense: 22,
        stamina: 18,
        weight: 0,
        height: 0,
        width: 0,
      },
    ],
    skipDuplicates: true,
  });

  await prisma.ratchet.createMany({
    data: [
        {
            name: "0-70",
            attack: 3,
            defense: 13,
            stamina: 14,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "0-80",
            attack: 3,
            defense: 12,
            stamina: 15,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "1-60",
            attack: 17,
            defense: 9,
            stamina: 4,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "1-80",
            attack: 17,
            defense: 4,
            stamina: 9,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "2-60",
            attack: 16,
            defense: 8,
            stamina: 6,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "2-70",
            attack: 10,
            defense: 12,
            stamina: 8,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "2-80",
            attack: 10,
            defense: 11,
            stamina: 9,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "3-60",
            attack: 15,
            defense: 9,
            stamina: 6,
            weight: 6,
            speed: 0,
            description: null,
        },
        {
            name: "3-70",
            attack: 15,
            defense: 8,
            stamina: 7,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "3-80",
            attack: 15,
            defense: 7,
            stamina: 8,
            weight: 7,
            speed: 0,
            description: null,
        },
        {
            name: "3-85",
            attack: 5,
            defense: 15,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "4-60",
            attack: 11,
            defense: 13,
            stamina: 6,
            weight: 6,
            speed: 0,
            description: null,
        },
        {
            name: "4-70",
            attack: 11,
            defense: 12,
            stamina: 7,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "4-80",
            attack: 11,
            defense: 11,
            stamina: 8,
            weight: 7,
            speed: 0,
            description: null,
        },
        {
            name: "4-55",
            attack: 7,
            defense: 11,
            stamina: 12,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "5-60",
            attack: 12,
            defense: 9,
            stamina: 9,
            weight: 7,
            speed: 0,
            description: null,
        },
        {
            name: "5-70",
            attack: 12,
            defense: 9,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "5-80",
            attack: 12,
            defense: 8,
            stamina: 10,
            weight: 7,
            speed: 0,
            description: null,
        },
        {
            name: "6-60",
            attack: 14,
            defense: 8,
            stamina: 8,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "6-80",
            attack: 14,
            defense: 6,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "7-60",
            attack: 8,
            defense: 14,
            stamina: 8,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "7-70",
            attack: 8,
            defense: 12,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "7-80",
            attack: 7,
            defense: 14,
            stamina: 9,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "9-60",
            attack: 13,
            defense: 10,
            stamina: 7,
            weight: 6,
            speed: 0,
            description: null,
        },
        {
            name: "9-70",
            attack: 13,
            defense: 10,
            stamina: 7,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "9-80",
            attack: 13,
            defense: 10,
            stamina: 7,
            weight: 7,
            speed: 0,
            description: null,
        },
        {
            name: "M-85",
            attack: 8,
            defense: 19,
            stamina: 13,
            weight: 0,
            speed: 0,
            description: null,
        },
    ],
    skipDuplicates: true,
  });

    await prisma.bit.createMany({
    data: [
        {
            name: "Accel",
            attack: 40,
            defense: 10,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Ball",
            attack: 15,
            defense: 25,
            stamina: 50,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Bound Spike",
            attack: 5,
            defense: 60,
            stamina: 30,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Cyclone",
            attack: 40,
            defense: 5,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Disc Ball",
            attack: 15,
            defense: 20,
            stamina: 55,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Dot",
            attack: 10,
            defense: 55,
            stamina: 25,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Elevate",
            attack: 30,
            defense: 15,
            stamina: 20,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Flat",
            attack: 40,
            defense: 15,
            stamina: 10,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Free Ball",
            attack: 10,
            defense: 25,
            stamina: 60,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "High Taper",
            attack: 30,
            defense: 25,
            stamina: 20,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "High Flat",
            attack: 40,
            defense: 15,
            stamina: 10,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Hexa",
            attack: 15,
            defense: 35,
            stamina: 35,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Low Flat",
            attack: 40,
            defense: 15,
            stamina: 10,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Metal Needle",
            attack: 5,
            defense: 40,
            stamina: 40,
            weight: 3,
            speed: 0,
            description: null,
        },
        {
            name: "Needle",
            attack: 5,
            defense: 40,
            stamina: 40,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Orb",
            attack: 15,
            defense: 25,
            stamina: 45,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Point",
            attack: 30,
            defense: 20,
            stamina: 25,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Quake",
            attack: 40,
            defense: 10,
            stamina: 10,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Rush",
            attack: 45,
            defense: 10,
            stamina: 10,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Spike",
            attack: 5,
            defense: 55,
            stamina: 25,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Spike",
            attack: 5,
            defense: 55,
            stamina: 25,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Taper",
            attack: 30,
            defense: 20,
            stamina: 30,
            weight: 2,
            speed: 0,
            description: null,
        },
        {
            name: "Gear Ball",
            attack: 15,
            defense: 25,
            stamina: 50,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Gear Flat",
            attack: 40,
            defense: 15,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Gear Needle",
            attack: 5,
            defense: 40,
            stamina: 40,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Gear Point",
            attack: 30,
            defense: 20,
            stamina: 25,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Glide",
            attack: 15,
            defense: 15,
            stamina: 60,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Metal Flat",
            attack: 40,
            defense: 15,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Rubber Flat",
            attack: 45,
            defense: 15,
            stamina: 5,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Semi Flat",
            attack: 30,
            defense: 15,
            stamina: 20,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Thin Needle",
            attack: 5,
            defense: 40,
            stamina: 40,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Wide Needle",
            attack: 5,
            defense: 40,
            stamina: 35,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Accel S",
            attack: 40,
            defense: 10,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Ball S",
            attack: 15,
            defense: 25,
            stamina: 50,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Dot S",
            attack: 10,
            defense: 55,
            stamina: 25,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Flat S",
            attack: 40,
            defense: 15,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Needle S",
            attack: 5,
            defense: 40,
            stamina: 40,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Orb S",
            attack: 15,
            defense: 25,
            stamina: 45,
            weight: 0,
            speed: 0,
            description: null,
        },
        {
            name: "Rush S",
            attack: 45,
            defense: 10,
            stamina: 10,
            weight: 0,
            speed: 0,
            description: null,
        }
    ],
    skipDuplicates: true,
  });

  console.log("Blade seed complete");
}

main()
  .then(async () => {
    await prisma.$disconnect();
    await pool.end();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    await pool.end();
    process.exit(1);
  });